name: 'Setup Node.js Environment'
description: 'Setup Node.js with npm caching for frontend'

inputs:
  node-version:
    description: 'Node.js version to setup'
    required: false
    default: '18'
  working-directory:
    description: 'Working directory for npm operations'
    required: false
    default: 'banking-ui'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
        cache-dependency-path: ${{ inputs.working-directory }}/package-lock.json

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: npm ci --prefer-offline --no-audit
