version: '3.8'

services:
  # Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: banking_db
      POSTGRES_USER: banking_user
      POSTGRES_PASSWORD: banking_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis for caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # API Gateway
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - account-service

  # Auth Service
  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/banking_db
      - SPRING_DATASOURCE_USERNAME=banking_user
      - SPRING_DATASOURCE_PASSWORD=banking_pass
    depends_on:
      - postgres

  # Account Service
  account-service:
    build: ./account-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/banking_db
      - SPRING_DATASOURCE_USERNAME=banking_user
      - SPRING_DATASOURCE_PASSWORD=banking_pass
    depends_on:
      - postgres

  # Payment Service
  payment-service:
    build: ./payment-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/banking_db
      - SPRING_DATASOURCE_USERNAME=banking_user
      - SPRING_DATASOURCE_PASSWORD=banking_pass
    depends_on:
      - postgres

  # Balance Service
  balance-service:
    build: ./balance-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/banking_db
      - SPRING_DATASOURCE_USERNAME=banking_user
      - SPRING_DATASOURCE_PASSWORD=banking_pass
    depends_on:
      - postgres

  # Transfer Service
  transfer-service:
    build: ./transfer-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/banking_db
      - SPRING_DATASOURCE_USERNAME=banking_user
      - SPRING_DATASOURCE_PASSWORD=banking_pass
    depends_on:
      - postgres

volumes:
  postgres_data:
