apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - port: 8081
    targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  selector:
    app: account-service
  ports:
  - port: 8084
    targetPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: audit-service
spec:
  selector:
    app: audit-service
  ports:
  - port: 8085
    targetPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: balance-service
spec:
  selector:
    app: balance-service
  ports:
  - port: 8086
    targetPort: 8086
---
apiVersion: v1
kind: Service
metadata:
  name: deposit-service
spec:
  selector:
    app: deposit-service
  ports:
  - port: 8087
    targetPort: 8087
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
  - port: 8088
    targetPort: 8088
---
apiVersion: v1
kind: Service
metadata:
  name: transfer-service
spec:
  selector:
    app: transfer-service
  ports:
  - port: 8089
    targetPort: 8089
---
apiVersion: v1
kind: Service
metadata:
  name: withdrawal-service
spec:
  selector:
    app: withdrawal-service
  ports:
  - port: 8091
    targetPort: 8091
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
  - port: 8090
    targetPort: 8090
---
