apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- prometheus/prometheus.yaml
- prometheus/custom-metrics.yaml
- grafana/grafana.yaml
- grafana/banking-dashboards.yaml
- jaeger/jaeger.yaml
- loki/loki.yaml
- ingress.yaml

commonLabels:
  stack: observability
