apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: banking-prod
  namespace: argocd
  labels:
    app: banking
    environment: prod
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: banking
  source:
    repoURL: https://github.com/your-org/banking-app.git
    targetRevision: v1.0.0
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: banking-prod
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
