apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
    component: gateway
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8090'
    prometheus.io/path: '/actuator/prometheus'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        component: gateway
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8090'
        prometheus.io/path: '/actuator/prometheus'
    spec:
      containers:
      - name: api-gateway
        image: banking/api-gateway:latest
        ports:
        - containerPort: 8090
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "k8s"
        - name: AUTH_SERVICE_URL
          value: "http://auth-service:8081"
        - name: ACCOUNT_SERVICE_URL
          value: "http://account-service:8084"
        - name: PAYMENT_SERVICE_URL
          value: "http://payment-service:8083"
        - name: AUDIT_SERVICE_URL
          value: "http://audit-service:8085"
        - name: BALANCE_SERVICE_URL
          value: "http://balance-service:8086"
        - name: DEPOSIT_SERVICE_URL
          value: "http://deposit-service:8087"
        - name: WITHDRAWAL_SERVICE_URL
          value: "http://withdrawal-service:8088"
        - name: TRANSFER_SERVICE_URL
          value: "http://transfer-service:8089"
        - name: NOTIFICATION_SERVICE_URL
          value: "http://notification-service:8091"
        - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
          value: "health,info,metrics,prometheus"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8090
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8090
          initialDelaySeconds: 30
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8090
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 30
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    app: api-gateway
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8090'
    prometheus.io/path: '/actuator/prometheus'
spec:
  selector:
    app: api-gateway
  ports:
  - port: 8090
    targetPort: 8090
    protocol: TCP
    name: http
  type: ClusterIP
