apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: auth-service-pdb
  labels:
    app: auth-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: auth-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: account-service-pdb
  labels:
    app: account-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: account-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: payment-service-pdb
  labels:
    app: payment-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: payment-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-gateway-pdb
  labels:
    app: api-gateway
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: api-gateway
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: banking-ui-pdb
  labels:
    app: banking-ui
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: banking-ui
