apiVersion: v1
kind: ServiceAccount
metadata:
  name: banking-service-account
  namespace: banking-app
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::YOUR-ACCOUNT:role/BankingAppRole
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: banking-app
  name: banking-role
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: banking-role-binding
  namespace: banking-app
subjects:
- kind: ServiceAccount
  name: banking-service-account
  namespace: banking-app
roleRef:
  kind: Role
  name: banking-role
  apiGroup: rbac.authorization.k8s.io
