apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: banking-app
  labels:
    app: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: banking-app
  labels:
    app: account-service
spec:
  selector:
    app: account-service
  ports:
  - port: 8084
    targetPort: 8084
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: banking-app
  labels:
    app: api-gateway
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  selector:
    app: api-gateway
  ports:
  - port: 80
    targetPort: 8090
    protocol: TCP
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: banking-db
  namespace: banking-app
spec:
  type: ExternalName
  externalName: banking-db.cluster-xyz.us-east-1.rds.amazonaws.com
  ports:
  - port: 5432
